# Generated by Django 5.0.2 on 2024-02-17 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('year', models.DateField(auto_now=True)),
                ('milage', models.IntegerField(default=0)),
            ],
        ),
    ]
